travis:
  secure:
    BINSTAR_TOKEN: Ga0eKMwe+52mmANg4BBaF2wueIFDurx+hmJjjdQR/hiqFUKrJa3Gg+8J/YigRycKsuVKZ9+Ll2065RENFJT66JUi/cQmL63R1py3ngYMOMgMkVy/wndmbKM3JJrF0X/RDIL/LusMmKh3dWqDIP6nLM2TvlEgYdGs8WyJRddAntfoeYa3rOc2ScBINb63Tf/6QKValyuO0fFq2JVFxfR2Plba7xiTCo4skARdet4LOafoXmWHJhe0atR6d8FQmDTqJ2ba4a0VPP8qw+MnS+VGbFjE10pg+TeXsvyYMBXkkWOag8w+SKEHMXiJm6QBm/E+3J0SYFxl7dm9FQllkxCRGKq1lXEXxbI7YyftRJBN6wk4N+Vq+AE9+OoshewAqHzKylANDF3Mw61QaKhPV5DtAHW0PutSWkpjmL5CJOXowM+gMJ+po5dpAWnmEkoN39c6FNYx6KRJ51nuirbJFAA0rT0JLm+SEX3pPfImOZf9Dgav/rLTF8RmnGOjQ1HxxLJTiRvizKnGqohnFbcQDUgA11vPysfMj80qPusbfTfKVGbtJ6rB5WCrppvpVI8n/m2ZcgTXQPg7IKZA3FfA/Fjc2Hv8xWPZ+Ud0I95/Yy/OcHH3MoEc7mcr9x3yDukAtjOibMZOs461u/qxAgeTMZgB0T4xC/IOK/XXO/YCFft0mtI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
