travis:
  secure:
    BINSTAR_TOKEN: lSjytza6RBwfHUzH5iGAiIvbxuJBfOWrL/4aGek4jIaM0SbJMbLJw7gzPqPYXEjaLS3AV+Ln/8FLPG1bH5VhCqbgEY5qPXPHXHgYX5FygHuoLgbbbE+Oo0scSF/EKgiD4S76eDDRzYuag6Je3oXJrMFTjlERM5mg6q8UGqDTyBor8dddSa2vx1ZppAd0g7z9FkiNEYztlYCPBMQuK8JrEpuVplmkq6e4RtQ8t39Yci/qj0hWvroALwsVldKlmNBAiRoKYL5Zz8RQXTU38yYRqdtG83MG4b6zG4YSUmTWgNnnYeHcypnl+dxe2p3WrYQWM8aNf/W3ror27PBwUiIHlRTtlB7Vxjao7Q63tVWW1QzadGc4Se/Egn8OobDGo+zd/EQOUKoGN9VTIXq636M3GAIvsow0z90EbHXV6NgC27R157Sw0TpovWeS5LsnlTsRb0QcQjcT5GtADFD1Bzb8QALYDylfv+aFMs7SGnpxB0cez49k6soHNJvoi52Qfpi2ulCnGVdXIIwwOHrH0mJeOCo1zCxF9YLxt3jGkBcVWC/3rQe8YqggMIjAWt8lw53PgIGzLaVkD6Sq3V/MDIXvNjsPx6w93V1ijAfi+H13PKJ8oVl7htjsSotgK4ztXTMSeg1s7kf8bRdvJu6MYcRS0tNnahH0YTjKJ2y6XobVniM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
